# Generated by Django 3.0.2 on 2020-01-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200120_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='c1',
            field=models.CharField(choices=[('1', 'RED'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'PURPLE'), ('5', 'YELLOW'), ('6', 'ORANGE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='c2',
            field=models.CharField(choices=[('1', 'RED'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'PURPLE'), ('5', 'YELLOW'), ('6', 'ORANGE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='c3',
            field=models.CharField(choices=[('1', 'RED'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'PURPLE'), ('5', 'YELLOW'), ('6', 'ORANGE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='c4',
            field=models.CharField(choices=[('1', 'RED'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'PURPLE'), ('5', 'YELLOW'), ('6', 'ORANGE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='play',
            name='c1',
            field=models.CharField(choices=[('1', 'RED'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'PURPLE'), ('5', 'YELLOW'), ('6', 'ORANGE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='play',
            name='c2',
            field=models.CharField(choices=[('1', 'RED'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'PURPLE'), ('5', 'YELLOW'), ('6', 'ORANGE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='play',
            name='c3',
            field=models.CharField(choices=[('1', 'RED'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'PURPLE'), ('5', 'YELLOW'), ('6', 'ORANGE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='play',
            name='c4',
            field=models.CharField(choices=[('1', 'RED'), ('2', 'GREEN'), ('3', 'BLUE'), ('4', 'PURPLE'), ('5', 'YELLOW'), ('6', 'ORANGE')], max_length=6),
        ),
    ]
