# Generated by Django 3.0.2 on 2020-01-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200120_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='numberoftries',
        ),
        migrations.RemoveField(
            model_name='play',
            name='number',
        ),
    ]
