# Generated by Django 3.0.2 on 2020-01-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200121_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='c1',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='c2',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='c3',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='c4',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=6),
        ),
        migrations.AlterField(
            model_name='play',
            name='c1',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=6),
        ),
        migrations.AlterField(
            model_name='play',
            name='c2',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=6),
        ),
        migrations.AlterField(
            model_name='play',
            name='c3',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=6),
        ),
        migrations.AlterField(
            model_name='play',
            name='c4',
            field=models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('PURPLE', 'Purple'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange')], max_length=6),
        ),
    ]
